name: veilid_support
description: Veilid Support Library
publish_to: 'none'
version: 1.0.2+0

environment:
  sdk: '>=3.2.0 <4.0.0'  

dependencies:
  async_tools: ^0.1.0
  bloc: ^8.1.3
  bloc_advanced_tools: ^0.1.0
  equatable: ^2.0.5
  fast_immutable_collections: ^10.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  meta: ^1.11.0
  mutex:
    path: ../mutex

  protobuf: ^3.1.0
  veilid:
    #   veilid: ^0.0.1
    path: ../../../veilid/veilid-flutter

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lint_hard: ^4.0.0
  test: ^1.25.2
