name: veilid_support
description: Veilid Support Library
publish_to: 'none'
version: 1.0.2+0

environment:
  sdk: '>=3.2.0 <4.0.0'  

dependencies:
  async_tools: ^0.1.4
  bloc: ^8.1.4
  bloc_advanced_tools: ^0.1.4
  charcode: ^1.3.1
  collection: ^1.18.0
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  loggy: ^2.0.3
  meta: ^1.12.0

  path: ^1.9.0
  path_provider: ^2.1.3
  protobuf: ^3.1.0
  veilid:
    #   veilid: ^0.0.1
    path: ../../../veilid/veilid-flutter

# dependency_overrides:
#   async_tools: 
#     path: ../../../dart_async_tools
#   bloc_advanced_tools: 
#     path: ../../../bloc_advanced_tools

dev_dependencies:
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lint_hard: ^4.0.0
  test: ^1.25.2
