name: bloc_tools
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  async_tools: ^0.1.0
  bloc: ^8.1.3
  equatable: ^2.0.5
  fast_immutable_collections: ^10.1.1
  freezed_annotation: ^2.4.1
  meta: ^1.11.0
  mutex:
    path: ../mutex

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  lint_hard: ^4.0.0
  test: ^1.25.2